// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbqcMM84Pip0AzDWEGEcrF6zIkA-nzsyw',
    appId: '1:421002891119:android:0f038e326433448d7f229a',
    messagingSenderId: '421002891119',
    projectId: 'campusclockslc-c63c9',
    storageBucket: 'campusclockslc-c63c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-fnGZXlKhx2uM8H_IsFujziZSt_W5gDM',
    appId: '1:421002891119:ios:50c35530d4c306e07f229a',
    messagingSenderId: '421002891119',
    projectId: 'campusclockslc-c63c9',
    storageBucket: 'campusclockslc-c63c9.firebasestorage.app',
    iosBundleId: 'com.example.campusClockSlc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhcUaWdnl9TTpkfCIPM6NTbwoufI0aoVQ',
    appId: '1:421002891119:web:862b1d1ad28bb8d57f229a',
    messagingSenderId: '421002891119',
    projectId: 'campusclockslc-c63c9',
    authDomain: 'campusclockslc-c63c9.firebaseapp.com',
    storageBucket: 'campusclockslc-c63c9.firebasestorage.app',
    measurementId: 'G-1L8TBH48QK',
  );
}
